Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 50
Metrics/ModuleLength:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ClassLength:
  Max: 200
Metrics/BlockLength:
  Max: 50
AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - 'db/*'
    - 'db/**/*'
    - 'bin/*'
    - 'config/*'
    - 'config/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'
Style/Documentation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false